// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr-qPu4KMqF4ZSJO_d6mIhKMCfo34jO_g',
    appId: '1:639845157697:web:0ab891bfa5f78ae1a8afc0',
    messagingSenderId: '639845157697',
    projectId: 'rekbro-app-id',
    authDomain: 'rekbro-app-id.firebaseapp.com',
    storageBucket: 'rekbro-app-id.firebasestorage.app',
    measurementId: 'G-6E73XH3BWX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDESXKErNLFeEK1cHmCci46OPjSefCPzmI',
    appId: '1:639845157697:android:0484e21a135bdbb9a8afc0',
    messagingSenderId: '639845157697',
    projectId: 'rekbro-app-id',
    storageBucket: 'rekbro-app-id.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfUyWmljsze9mNSWBLktNzisfEltpQTY4',
    appId: '1:639845157697:ios:c43d039e8260d270a8afc0',
    messagingSenderId: '639845157697',
    projectId: 'rekbro-app-id',
    storageBucket: 'rekbro-app-id.firebasestorage.app',
    iosBundleId: 'com.example.rekbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfUyWmljsze9mNSWBLktNzisfEltpQTY4',
    appId: '1:639845157697:ios:c43d039e8260d270a8afc0',
    messagingSenderId: '639845157697',
    projectId: 'rekbro-app-id',
    storageBucket: 'rekbro-app-id.firebasestorage.app',
    iosBundleId: 'com.example.rekbro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBr-qPu4KMqF4ZSJO_d6mIhKMCfo34jO_g',
    appId: '1:639845157697:web:ff2c65d5d5c71ddba8afc0',
    messagingSenderId: '639845157697',
    projectId: 'rekbro-app-id',
    authDomain: 'rekbro-app-id.firebaseapp.com',
    storageBucket: 'rekbro-app-id.firebasestorage.app',
    measurementId: 'G-THSFYW165D',
  );
}
